// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dex/pair.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Pair struct {
	PriceDenom Denom                                  `protobuf:"varint,1,opt,name=priceDenom,proto3,enum=seiprotocol.seichain.dex.Denom" json:"price_denom"`
	AssetDenom Denom                                  `protobuf:"varint,2,opt,name=assetDenom,proto3,enum=seiprotocol.seichain.dex.Denom" json:"asset_denom"`
	Ticksize   github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=ticksize,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"tick_size"`
}

func (m *Pair) Reset()         { *m = Pair{} }
func (m *Pair) String() string { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()    {}
func (*Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4350ebee878f69a, []int{0}
}
func (m *Pair) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Pair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Pair.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Pair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pair.Merge(m, src)
}
func (m *Pair) XXX_Size() int {
	return m.Size()
}
func (m *Pair) XXX_DiscardUnknown() {
	xxx_messageInfo_Pair.DiscardUnknown(m)
}

var xxx_messageInfo_Pair proto.InternalMessageInfo

func (m *Pair) GetPriceDenom() Denom {
	if m != nil {
		return m.PriceDenom
	}
	return Denom_SEI
}

func (m *Pair) GetAssetDenom() Denom {
	if m != nil {
		return m.AssetDenom
	}
	return Denom_SEI
}

type BatchContractPair struct {
	ContractAddr string  `protobuf:"bytes,1,opt,name=contractAddr,proto3" json:"contract_addr"`
	Pairs        []*Pair `protobuf:"bytes,2,rep,name=pairs,proto3" json:"pairs"`
}

func (m *BatchContractPair) Reset()         { *m = BatchContractPair{} }
func (m *BatchContractPair) String() string { return proto.CompactTextString(m) }
func (*BatchContractPair) ProtoMessage()    {}
func (*BatchContractPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4350ebee878f69a, []int{1}
}
func (m *BatchContractPair) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BatchContractPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BatchContractPair.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BatchContractPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchContractPair.Merge(m, src)
}
func (m *BatchContractPair) XXX_Size() int {
	return m.Size()
}
func (m *BatchContractPair) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchContractPair.DiscardUnknown(m)
}

var xxx_messageInfo_BatchContractPair proto.InternalMessageInfo

func (m *BatchContractPair) GetContractAddr() string {
	if m != nil {
		return m.ContractAddr
	}
	return ""
}

func (m *BatchContractPair) GetPairs() []*Pair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

func init() {
	proto.RegisterType((*Pair)(nil), "seiprotocol.seichain.dex.Pair")
	proto.RegisterType((*BatchContractPair)(nil), "seiprotocol.seichain.dex.BatchContractPair")
}

func init() { proto.RegisterFile("dex/pair.proto", fileDescriptor_d4350ebee878f69a) }

var fileDescriptor_d4350ebee878f69a = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x3f, 0x4f, 0xfa, 0x40,
	0x18, 0xc7, 0x5b, 0xf8, 0xfd, 0x8c, 0x3d, 0x14, 0x42, 0xe3, 0xd0, 0x30, 0xb4, 0x84, 0xc1, 0xb0,
	0x70, 0x4d, 0x30, 0x4e, 0x0e, 0xc6, 0x4a, 0xe2, 0x4a, 0xba, 0x98, 0xb8, 0x90, 0xe3, 0xee, 0x02,
	0x17, 0x6c, 0xaf, 0xb9, 0x3b, 0x12, 0x74, 0x75, 0x74, 0xf1, 0x65, 0x31, 0x32, 0x1a, 0x87, 0xc6,
	0xc0, 0xd6, 0x57, 0x61, 0xee, 0x0a, 0x8a, 0x03, 0x83, 0xd3, 0x3d, 0xff, 0xbe, 0x9f, 0xcb, 0xf7,
	0x79, 0x40, 0x9d, 0xd0, 0x45, 0x98, 0x21, 0x26, 0x60, 0x26, 0xb8, 0xe2, 0xae, 0x27, 0x29, 0x33,
	0x11, 0xe6, 0x8f, 0x50, 0x52, 0x86, 0xa7, 0x88, 0xa5, 0x90, 0xd0, 0x45, 0xeb, 0x6c, 0xc2, 0x27,
	0xdc, 0xb4, 0x42, 0x1d, 0x95, 0xf3, 0xad, 0x86, 0xd6, 0xd3, 0x74, 0x9e, 0xc8, 0xb2, 0xd0, 0x79,
	0xa9, 0x80, 0x7f, 0x43, 0xc4, 0x84, 0x3b, 0x04, 0x20, 0x13, 0x0c, 0xd3, 0x01, 0x4d, 0x79, 0xe2,
	0xd9, 0x6d, 0xbb, 0x5b, 0xef, 0x07, 0xf0, 0x10, 0x1e, 0x9a, 0xb1, 0xa8, 0x51, 0xe4, 0x41, 0xcd,
	0xc8, 0x46, 0x44, 0x17, 0xe2, 0x3d, 0x86, 0x26, 0x22, 0x29, 0xa9, 0x2a, 0x89, 0x95, 0x3f, 0x10,
	0x8d, 0x6c, 0x47, 0xfc, 0x61, 0xb8, 0xf7, 0xe0, 0x58, 0x31, 0x3c, 0x93, 0xec, 0x99, 0x7a, 0xd5,
	0xb6, 0xdd, 0x75, 0xa2, 0xab, 0x65, 0x1e, 0x58, 0x1f, 0x79, 0x70, 0x3e, 0x61, 0x6a, 0x3a, 0x1f,
	0x43, 0xcc, 0x93, 0x10, 0x73, 0x99, 0x70, 0xb9, 0x7d, 0x7a, 0x92, 0xcc, 0x42, 0xf5, 0x94, 0x51,
	0x09, 0x07, 0x14, 0x17, 0x79, 0xe0, 0x68, 0xc2, 0x48, 0x23, 0xe2, 0x6f, 0x58, 0xe7, 0xd5, 0x06,
	0xcd, 0x08, 0x29, 0x3c, 0xbd, 0xe5, 0xa9, 0x12, 0x08, 0x2b, 0xb3, 0x92, 0x4b, 0x70, 0x82, 0xb7,
	0xf9, 0x0d, 0x21, 0xc2, 0x2c, 0xc5, 0x89, 0x9a, 0x45, 0x1e, 0x9c, 0xee, 0xea, 0x23, 0x44, 0x88,
	0x88, 0x7f, 0x8d, 0xb9, 0xd7, 0xe0, 0xbf, 0xbe, 0x90, 0xf4, 0x2a, 0xed, 0x6a, 0xb7, 0xd6, 0xf7,
	0x0f, 0x5b, 0xd6, 0xbf, 0x44, 0x4e, 0x91, 0x07, 0xa5, 0x20, 0x2e, 0x9f, 0xe8, 0x6e, 0xb9, 0xf6,
	0xed, 0xd5, 0xda, 0xb7, 0x3f, 0xd7, 0xbe, 0xfd, 0xb6, 0xf1, 0xad, 0xd5, 0xc6, 0xb7, 0xde, 0x37,
	0xbe, 0xf5, 0xd0, 0xdb, 0xb3, 0x29, 0x29, 0xeb, 0xed, 0xb0, 0x26, 0x31, 0xdc, 0x70, 0x11, 0xea,
	0x13, 0x1b, 0xc7, 0xe3, 0x23, 0xd3, 0xbf, 0xf8, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x21, 0x67, 0x4f,
	0x78, 0x36, 0x02, 0x00, 0x00,
}

func (m *Pair) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Pair) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Pair) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Ticksize.Size()
		i -= size
		if _, err := m.Ticksize.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPair(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.AssetDenom != 0 {
		i = encodeVarintPair(dAtA, i, uint64(m.AssetDenom))
		i--
		dAtA[i] = 0x10
	}
	if m.PriceDenom != 0 {
		i = encodeVarintPair(dAtA, i, uint64(m.PriceDenom))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BatchContractPair) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BatchContractPair) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BatchContractPair) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Pairs) > 0 {
		for iNdEx := len(m.Pairs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Pairs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPair(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ContractAddr) > 0 {
		i -= len(m.ContractAddr)
		copy(dAtA[i:], m.ContractAddr)
		i = encodeVarintPair(dAtA, i, uint64(len(m.ContractAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPair(dAtA []byte, offset int, v uint64) int {
	offset -= sovPair(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Pair) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PriceDenom != 0 {
		n += 1 + sovPair(uint64(m.PriceDenom))
	}
	if m.AssetDenom != 0 {
		n += 1 + sovPair(uint64(m.AssetDenom))
	}
	l = m.Ticksize.Size()
	n += 1 + l + sovPair(uint64(l))
	return n
}

func (m *BatchContractPair) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddr)
	if l > 0 {
		n += 1 + l + sovPair(uint64(l))
	}
	if len(m.Pairs) > 0 {
		for _, e := range m.Pairs {
			l = e.Size()
			n += 1 + l + sovPair(uint64(l))
		}
	}
	return n
}

func sovPair(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPair(x uint64) (n int) {
	return sovPair(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Pair) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPair
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Pair: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Pair: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceDenom", wireType)
			}
			m.PriceDenom = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPair
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PriceDenom |= Denom(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetDenom", wireType)
			}
			m.AssetDenom = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPair
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetDenom |= Denom(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ticksize", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPair
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPair
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPair
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Ticksize.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPair(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPair
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BatchContractPair) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPair
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BatchContractPair: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BatchContractPair: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPair
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPair
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPair
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pairs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPair
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPair
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPair
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pairs = append(m.Pairs, &Pair{})
			if err := m.Pairs[len(m.Pairs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPair(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPair
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPair(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPair
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPair
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPair
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPair
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPair
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPair
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPair        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPair          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPair = fmt.Errorf("proto: unexpected end of group")
)
